version: '2.3'
services:
  consul:
    image: "progrium/consul"
    restart: always
    container_name: consul
    hostname: "consul"
    volumes:
      - ./volumes/consul/data:/volumes/data/consul
      - ./volumes/consul/config:/volumes/config/consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "-server -bootstrap -ui-dir /ui -join=127.0.0.1 "
networks:
  default:
    external:
      name: consul