# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: Elasticsearch
  type: elasticsearch
  typeLogoUrl: public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg
  access: proxy
  url: http://<elasticsearch-ip>:9200
  password: ''
  user: ''
  database: <index-pattern-name>*
  basicAuth: false
  isDefault: false
  jsonData: {esVersion: 70, keepCookies: [], maxConcurrentShardRequests: 256, timeField: "@timestamp"}
  esVersion: 70
  keepCookies: []
  maxConcurrentShardRequests: 256
  timeField: "@timestamp"
  readOnly: false

